### ISSUE TITLE
OSError: [Errno 2] No such file or directory while running pipeline.

### ISSUE THREAD

**Issue by winterhoney8146** [rennu/dpg#4]
Hi, I'm trying to create .ply file by using example image set.

By using terminal on mac, when I run this pipeline,
"
/opt/dpg/pipeline.py --input /datasets/images --output /datasets/output_dense --sfm-type incremental --geomodel f --run-openmvg --run-openmvs --densify
"

I get
"
Traceback (most recent call last):
  File "/opt/dpg/pipeline.py", line 387, in <module>
    runCommands(commands)
  File "/opt/dpg/pipeline.py", line 368, in runCommands
    rc = runCommand(map(str, instruction['command']))
  File "/opt/dpg/pipeline.py", line 357, in runCommand
    p = subprocess.Popen(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
"

Can I get some advice to solve this issue?

**Comment by rennu** [comment]
Hi,

I assume you are trying to run the pipeline in mac terminal and that you are not using docker? Have you installed the other required software (OpenMVG and OpenMVS)? The error you are getting is due to the script being unable to execute an executable of either OpenMVG or OpenMVS because it's not found.

If you have not yet installed the other required software, the easiest way to setup the pipeline on mac is to first [install docker](https://docs.docker.com/v17.12/docker-for-mac/install/), then build the docker image and finally running the container (see the instructions).

The default options in docker for mac restrict heavily container performance. To fix this, open docker settings and increase the amount of cores and memory available for containers.
